---
Gemfile:
  required:
    ':development, :test, :system_tests':
      - gem: 'puppet-openstack_spec_helper'
        git: 'https://git.openstack.org/openstack/puppet-openstack_spec_helper'
Rakefile:
  default_disabled_lint_checks:
  - '80chars'
  - 'class_inherits_from_params_class'
  - 'only_variable_string'
