#!/bin/bash
#
# functions - puppet-openstack_spec_helper specific functions
#

install_module() {
  if [ -e /usr/zuul-env/bin/zuul-cloner ] ; then
      /usr/zuul-env/bin/zuul-cloner --cache-dir /opt/git \
          git://git.openstack.org openstack/puppet-openstack-cookiecutter
  else
      git clone git://git.openstack.org/openstack/puppet-openstack-cookiecutter openstack/puppet-openstack-cookiecutter
  fi
  cd openstack/puppet-openstack-cookiecutter
  export PUPPET_GEM_VERSION="~> $PUPPET_MAJOR_VERSION"
  source functions
  prepare_environment
}
